### ISSUE TITLE
Backslash instead of Slash in path

### ISSUE THREAD

**Issue by CarlosAzocar** [asvetliakov/move-imports#1]
S.O: Window 10 Pro x64
VSCode: v1.12.1

Backslash instead of Slash in path before renaming

# Before renaming

![2017-05-11](https://cloud.githubusercontent.com/assets/18235355/25980364/01120b6c-369c-11e7-8001-b2cce9aff5be.png)

After # renaming
![2017-05-11 1](https://cloud.githubusercontent.com/assets/18235355/25980370/0a52a844-369c-11e7-97f2-2454c7139073.png)

**Comment by asvetliakov** [comment]
Pushed version 0.0.4, thanks for reporting
