### ISSUE TITLE
Can't find this in VSCode Ex!

### ISSUE THREAD

**Issue by thearabbit** [asvetliakov/move-imports#11]
Can't find this in VSCode Ex!

**Comment by asvetliakov** [comment]
I unpublished the extension due to few critical unresolved bugs. After i'll complete refactor and fix them i publish it again. 
Sorry for any inconvenience, in meantime you can use move-ts extension to do the same task (without drag & drop though)

**Comment by thearabbit** [comment]
I base on `js and vue`, could I use `move-ts`?

**Comment by asvetliakov** [comment]
Unfortunately i don't know 😄 So just try it!
