### ISSUE TITLE
Unpublished extension

### ISSUE THREAD

**Issue by ackvf** [asvetliakov/move-imports#12]
The extension can't be installed from marketplace any more, is it discontinued?
https://marketplace.visualstudio.com/items?itemName=asvetliakov.move-imports

**Comment by alexgorbatchev** [comment]
ditto

**Comment by asvetliakov** [comment]
The extension was unpublished due to critical bugs, complains, etc... I republish it when i'll got it fixed and refactored (out of time now). Sorry.

In meantime, you can use [Move-TS](https://marketplace.visualstudio.com/items?itemName=stringham.move-ts) extension, it does almost the same.

**Comment by derwaldgeist** [comment]
Does Move-TS really work for regular ES6? It doesn't mention it.

**Comment by asvetliakov** [comment]
@derwaldgeist You don't need any extensions now. TS 3.0+ supports renaming imports out the box

**Comment by derwaldgeist** [comment]
I don't use TypeScript. That's why I was asking for ES6 :-)

**Comment by asvetliakov** [comment]
You're using builtin TS server provided by vscode then.
