### ISSUE TITLE
Exclude files excluded by .gitignore

### ISSUE THREAD

**Issue by MeirionHughes** [asvetliakov/move-imports#2]
This is picking up changes to my dist folder; Ideally this plugin should read the gitignore and ignore the same files/folders. 

I've also tried adding (user settings)

```
"move-imports.excludedRegexp": "/node_modules|dist|coverage/"
```

but when I start-up up vscode on some projects its giveing me warning about files in these directories.

**Comment by asvetliakov** [comment]
Sounds like a good improvement
In meantime, try to add ```()``` to your regex, i.e. ```"/(node_modules|dist|coverage)/"```
