### ISSUE TITLE
back slashes after move the file

### ISSUE THREAD

**Issue by radziksh** [asvetliakov/move-imports#5]
after I moved the file I see "back slashes": 
![screenshot_324](https://user-images.githubusercontent.com/1275228/27799520-25d529ce-601e-11e7-84b6-0621ce2251ad.png)

vs code 1.13.1
windows 10
node 7.4.0

**Comment by asvetliakov** [comment]
Which version of plugin are you using? I fixed this problem in 0.0.4

**Comment by radziksh** [comment]
I installed it an hour ago from: https://marketplace.visualstudio.com/items?itemName=asvetliakov.move-imports
looks like: 0.0.7

**Comment by asvetliakov** [comment]
Ok. try version 0.0.8. Let me know if the problem is still persist. Thanks for bug report!

**Comment by radziksh** [comment]
Thank you, it works, it was the quickest fix of the issue in my life :D
