### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by adenflorian** [asvetliakov/move-imports#7]
Hi, I really like this extension, it's very useful. I think more people and companies would be more comfortable using it if you had a LICENSE.md with an open source license in it (preferably MIT License) in the project's root folder.

**Comment by asvetliakov** [comment]
Thanks for suggestion!

**Comment by adenflorian** [comment]
Could you also publish a new version of the extension to the marketplace with the new license?

**Comment by asvetliakov** [comment]
@AdenFlorian  published 0.0.9 version
